[workspace]
members = ["crates/core", "crates/cli"]
resolver = "2"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "deny", priority = 1 }
redundant_clone = { level = "deny", priority = 2 }
clone_on_copy = { level = "deny", priority = 2 }
needless_collect = { level = "deny", priority = 2 }
