[workspace]
members = ["crates/input-parser"]
resolver = "2"

[package]
name = "typegin"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.3.12", features = [
  "sqlite",
  "returning_clauses_for_sqlite_3_35",
] }
getset = "0.1.7"
input-parser = { path = "crates/input-parser" }
serde = { version = "1.0", features = ["derive"] }
tokio = "1.53.1"
toml = "0.8"

[dev-dependencies]
diesel_migrations = "2.2.0"
rstest = "0.26"
