pub mod dialogue_node_id;
pub mod dialogue_option_id;
pub mod npc_id;
pub mod object_id;
pub mod room_id;
pub mod trigger_id;

/// Defines a symbolic-string newtype id: `new`, `Display`, and a conversion
/// from `String`.
///
/// Every world-data id (object, room, npc, dialogue node, dialogue option)
/// shares this exact shape — the key is the id's stable symbolic name from
/// authored world data (e.g. `iron-key`), never a numeric surrogate.
///
/// Kept deliberately minimal: only generate what call sites actually use
/// (`new`, `Display`, `From<String>` for the one raw-string-to-id conversion
/// in `Object::from_data`'s door target). Add more conversions if a real call
/// site needs them, rather than carrying unused surface for every id type.
macro_rules! define_id {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[derive(
            Debug,
            Clone,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::serde::Serialize,
            ::serde::Deserialize
        )]
        pub struct $name(String);

        impl $name {
            #[must_use]
            pub fn new(value: impl Into<String>) -> Self {
                $name(value.into())
            }
        }

        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                write!(f, "{}", self.0)
            }
        }

        impl From<String> for $name {
            fn from(value: String) -> Self {
                $name(value)
            }
        }
    };
}

pub(crate) use define_id;

// `camelCase` shorthand macros for each id's `new`, e.g. `roomId!("cellar")`
// for `RoomId::new("cellar")`. `#[macro_export]` is what makes each callable
// as `core::roomId!(...)` from outside the crate (e.g. from
// `crates/core/tests/*.rs`) or as `crate::roomId!(...)` from within it — a
// plain `macro_rules!` is otherwise only reachable unqualified, and only
// where legacy textual scoping happens to reach.
//
// Written out individually rather than generated by a `define_id!`-style
// meta-macro: a macro produced by expanding another macro can't be named by
// an absolute path (`crate::roomId!`/`core::roomId!`) — only a `macro_rules!`
// written directly in source can be, and every call site here needs that.
//
// Named `camelCase` deliberately: it keeps each macro from colliding with
// the `snake_case` module of the same id (`room_id!` would collide with
// `pub mod room_id`), and reads as a call-site shorthand rather than a
// second way to spell the module path.
#[macro_export]
macro_rules! roomId {
    ($value:expr) => {
        $crate::keys::room_id::RoomId::new($value)
    };
}

#[macro_export]
macro_rules! objectId {
    ($value:expr) => {
        $crate::keys::object_id::ObjectId::new($value)
    };
}

#[macro_export]
macro_rules! npcId {
    ($value:expr) => {
        $crate::keys::npc_id::NpcId::new($value)
    };
}

#[macro_export]
macro_rules! dialogueNodeId {
    ($value:expr) => {
        $crate::keys::dialogue_node_id::DialogueNodeId::new($value)
    };
}

#[macro_export]
macro_rules! dialogueOptionId {
    ($value:expr) => {
        $crate::keys::dialogue_option_id::DialogueOptionId::new($value)
    };
}

#[macro_export]
macro_rules! triggerId {
    ($value:expr) => {
        $crate::keys::trigger_id::TriggerId::new($value)
    };
}

/// Outcome of resolving a player-typed noun against a set of named things.
///
/// Shared by every "resolve this name" lookup in the engine — world objects
/// ([`ObjectId`](crate::keys::object_id::ObjectId)) and use-with targets
/// ([`Target`](crate::interaction::Target)) alike — so the three cases
/// (found, matched more than one name, matched none) are defined once.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Resolution<T> {
    Found(T),
    Ambiguous { ids: Vec<T>, alias: String },
    NotFound,
}
